[package]
name = "kuro"
version = "0.0.0"
edition = "2021"
license = "GPL-3.0"
description = "A cross-platform dotfiles/configuration management tool"
homepage = "https://github.com/KevinSilvester/kuro"
repository = "https://github.com/KevinSilvester/kuro"
readme = "README.md"
categories = ["utilities", "system"]
keywords = ["dotfiles", "configuration", "management", "cross-platform"]

[dependencies]
