[kuro_options]
editor = "nvim"

[[dots]]
name = "nvim"
dest = { windows = "~/AppData/Local/nvim", unix = "~/.config/nvim" }
src = { git = "https://github.com/KevinSilvester/nvim-config.git" }

[[dots]]
name = "wezterm"
dest = "~/.config/wezterm"
src = { git = "https://github.com/KevinSilvester/wezterm-config.git" }

[[dots]]

